events{}

http{

    limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;

    upstream backend {
        server backend-1:3000;
        server backend-2:3000;
        server backend-3:3000;
    }

    server {
        listen 80;

        location / {
            limit_req zone=one burst=20;
            proxy_pass http://backend;
        }
    }

}